apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otel-demo-dev
  namespace: openshift-gitops
spec:
  description: OTel Demo - Dev environment
  sourceRepos:
    - https://github.com/tarosaiba/argo-rollouts-sample.git
  destinations:
    - namespace: otel-demo-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
