# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-cart
  labels:
    helm.sh/chart: opentelemetry-demo-0.40.7
    
    opentelemetry.io/name: valkey-cart
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: valkey-cart
    app.kubernetes.io/name: valkey-cart
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: valkey-cart
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: valkey-cart
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: valkey-cart
        app.kubernetes.io/name: valkey-cart
      annotations:
        io.opentelemetry.discovery.metrics/config: |
          username: valkey
          collection_interval: 10s
        io.opentelemetry.discovery.metrics/enabled: "true"
        io.opentelemetry.discovery.metrics/scraper: redis
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: otel-demo
      containers:
        - name: valkey-cart
          image: 'valkey/valkey:9.0.1-alpine3.23'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 6379
              name: valkey-cart
          env:
            []
          resources:
            limits:
              memory: 20Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
      volumes:
