# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-reviews
  labels:
    helm.sh/chart: opentelemetry-demo-0.40.7
    
    opentelemetry.io/name: product-reviews
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: product-reviews
    app.kubernetes.io/name: product-reviews
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: product-reviews
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: product-reviews
        
        app.kubernetes.io/version: "2.2.0"
        app.kubernetes.io/component: product-reviews
        app.kubernetes.io/name: product-reviews
      annotations:
        resource.opentelemetry.io/service.namespace: otel-demo
    spec:
      serviceAccountName: otel-demo
      containers:
        - name: product-reviews
          image: 'ghcr.io/open-telemetry/demo:2.2.0-product-reviews'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 3551
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: OPENAI_API_KEY
              value: dummy
            - name: LLM_MODEL
              value: astronomy-llm
            - name: LLM_HOST
              value: llm
            - name: LLM_PORT
              value: "8000"
            - name: LLM_BASE_URL
              value: http://$(LLM_HOST):$(LLM_PORT)/v1
            - name: PRODUCT_REVIEWS_PORT
              value: "3551"
            - name: PRODUCT_CATALOG_ADDR
              value: product-catalog:8080
            - name: FLAGD_HOST
              value: flagd
            - name: FLAGD_PORT
              value: "8013"
            - name: DB_CONNECTION_STRING
              value: host=postgresql user=otelu password=otelp dbname=otel
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: python
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4317
          resources:
            limits:
              memory: 100Mi
          volumeMounts:
      volumes:
