# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-reviews
  labels:
    helm.sh/chart: opentelemetry-demo-0.40.7
    
    opentelemetry.io/name: product-reviews
    
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/component: product-reviews
    app.kubernetes.io/name: product-reviews
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3551
      name: tcp-service
      targetPort: 3551
  selector:
    
    opentelemetry.io/name: product-reviews
