apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo-dev

resources:
- ../../base

  # dev: lower replicas, debug log level for load-generator
  # Set namespace for analysis FQDN (controller runs in argo-rollouts ns)
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: load-generator
    spec:
      replicas: 1
  target:
    kind: Deployment
    name: load-generator
- patch: |-
    - op: replace
      path: /spec/strategy/blueGreen/prePromotionAnalysis/args/1/value
      value: otel-demo-dev
  target:
    kind: Rollout
    name: frontend

images:
- name: ghcr.io/open-telemetry/demo:2.2.0-frontend
  newName: ghcr.io/open-telemetry/demo
  newTag: pre-release-frontend
