apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo-dev

resources:
  - ../../base

patches:
  # dev: lower replicas, debug log level for load-generator
  - target:
      kind: Deployment
      name: load-generator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: load-generator
      spec:
        replicas: 1
