apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo-prod
  namespace: openshift-gitops
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: "#notification-test"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "#notification-test"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "#notification-test"
spec:
  project: otel-demo-prod
  source:
    repoURL: https://github.com/tarosaiba/argo-rollouts-sample.git
    targetRevision: v1.1.0
    path: otel-demo/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
  # No automated sync — prod requires manual sync
