apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-demo
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: otel-demo-dev
            project: otel-demo-dev
  template:
    metadata:
      name: "otel-demo-{{env}}"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.slack: "#notification-test"
        notifications.argoproj.io/subscribe.on-health-degraded.slack: "#notification-test"
        notifications.argoproj.io/subscribe.on-sync-failed.slack: "#notification-test"
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/tarosaiba/argo-rollouts-sample.git
        targetRevision: main
        path: "otel-demo/overlays/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true
