apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-demo
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: otel-demo-dev
            project: otel-demo-dev
            syncPolicy: automated
            selfHeal: "true"
          - env: stg
            namespace: otel-demo-stg
            project: otel-demo-stg
            syncPolicy: automated
            selfHeal: "false"
          - env: prod
            namespace: otel-demo-prod
            project: otel-demo-prod
            syncPolicy: manual
            selfHeal: "false"
  template:
    metadata:
      name: "otel-demo-{{env}}"
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/tarosaiba/argo-rollouts-sample.git
        targetRevision: main
        path: "otel-demo/overlays/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true
  templatePatch: |
    {{- if eq .syncPolicy "automated" }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: {{ .selfHeal }}
    {{- end }}
